#!/usr/bin/env ANSIBLE_NOCOWS=1 ansible-playbook
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - temp_folder: "/tmp/pimp_my_temp"
    - brew_packages:
      - bash-completion
      - docker-completion
      - docker-compose-completion
      - gradle-completion
      - maven-completion
      - pip-completion
      - vagrant-completion
      - autojump
      - awscli
      - coreutils
      - ccze
      - htop
      - httpie
      - jq
      - lynx
      - mdp
      - micro
      - most
      - mtr
      - nmap
      - pv
      - tree
      - watch
      - wget
      - youtube-dl
      - grc
      - git
    - dmg_files:
      - name: Idea
        url: https://download.jetbrains.com/idea/ideaIC-2019.3.4-jbr8.dmg
        filename: ideaIC-2019.3.4-jbr8.dmg
      - name: keepass
        url: https://github.com/keepassxreboot/keepassxc/releases/download/2.5.4/KeePassXC-2.5.4.dmg
        filename: KeePassXC-2.5.4.dmg
    - applications:
      - name: iTerm
        url: https://iterm2.com/downloads/stable/iTerm2-3_3_9.zip
        filename: iTerm2-3_3_9.zip
        need_unpack: yes
  tasks:
    - name: Populate bash profile
      tags: bash
      block:
        - name: Understand who I am
          become: false
          command: whoami
          register: raw_whoami
        - name: Ensure bash is set as user shell
          user:
            name: "{{ raw_whoami.stdout }}"
            shell: /bin/bash
        - name: Template bash_profile
          template:
            src: bash.bashrc
            dest: "~/.bash_profile"
        - name: Transform bashrc
          file:
            src: ~/.bash_profile
            dest: ~/.bashrc
            state: link
        - name: Make home opt dir
          file:
            dest: ~/opt
            state: directory
        - name: Template GRC resource
          template:
            src: grc.bashrc
            dest: ~/opt/grc.bashrc

    - name: Setup needed brew packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present

    - name: Create temp
      file:
        path: "{{ temp_folder }}"
        state: directory

    - name: Download applications
      get_url:
        url: "{{ item.url }}"
        dest: "{{ temp_folder }}/{{ item.filename }}"
      loop: "{{ applications }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Download dmg_files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ temp_folder }}/{{ item.filename }}"
      loop: "{{ dmg_files }}"
      loop_control:
        label: "{{ item.name }}"
